/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ValaClass {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ValaClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValaClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libobjectJNI.delete_ValaClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    libobjectJNI.ValaClass_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libobjectJNI.ValaClass_name_get(swigCPtr, this);
  }

  public ValaClass() {
    this(libobjectJNI.new_ValaClass(), true);
  }

  public String append_to_name(String suffix) {
    return libobjectJNI.ValaClass_append_to_name(swigCPtr, this, suffix);
  }

}
